# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration parameters
boxRam = 2048                      # Ram in MB
boxCpus = 2                        # Number of CPU core

ipythonPort = 1088                 # Ipython port to forward (also set in IPython notebook config)

Vagrant.configure(2) do |config|
  config.vm.define "sparkvm" do |master|
    master.vm.box = "ubuntu/trusty32"
    master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort   # IPython port (set in notebook config)
    master.vm.hostname = "sparkvm"

    master.vm.provider :virtualbox do |v|
      v.name = master.vm.hostname.to_s
      v.customize ["modifyvm", :id, "--memory", "#{boxRam}"]
      v.customize ["modifyvm", :id, "--cpus", "#{boxCpus}"]
    end
    master.vm.provision :shell, :path => "provision_spark_node.sh"
  end
end
