# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration parameters
boxRam = 4096                      # Ram in MB
boxCpus = 2                        # Number of CPU core

hostname = "sparkrvm"
privateNetworkIp = "192.168.128.1"    # Starting IP range for the private network between nodes

# Create hosts data

hosts = "#{privateNetworkIp} sparkrvm sparkrvm\n"

$hosts_data = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
#{hosts}
EOF
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "#{hostname}" do |master|
    master.vm.box = "ubuntu/vivid64"
    master.vm.network :forwarded_port, host: 4040, guest: 4040   # SparkUI port
    master.vm.network :forwarded_port, host: 8080, guest: 8080   # Zeppelin default port
    master.vm.network :forwarded_port, host: 8081, guest: 8081   # Zeppelin callback port
    master.vm.network :private_network, ip: "#{privateNetworkIp}", :netmask => "255.255.255.0", virtualbox__intnet: true
    master.vm.hostname = "#{hostname}"

    master.vm.provider :virtualbox do |v|
      v.name = master.vm.hostname.to_s
      v.customize ["modifyvm", :id, "--memory", "#{boxRam}"]
      v.customize ["modifyvm", :id, "--cpus", "#{boxCpus}"]
    end

    master.vm.provision :shell, :inline => $hosts_data
    master.vm.provision :shell, :path => "provision_spark_node.sh"
    master.vm.provision :shell, :path => "provision_spark_app.sh"
  end
end
